CFLAGS += -W -Wall
all: queue process process_simulation signal_VS_realtime_signal signalset_with_binary_tree menu tools

queue:

process:

process_simulation: tools.c process.c queue.c processmodel.c 

signal_VS_realtime_signal:

signalset_with_signal_mask: tools.c menu.c 

signalset_with_binary_tree: tools.c menu.c

childwaiti:

# my libs
menu:

tools:

clean:
	$(RM) *.o 
