CFLAGS += -W -Wall
all: queue process process_simulation signal_VS_realtime_signal signalset_with_binary_tree menu tools

queue:

process:

process_simulation: tools.c process.c queue.c processmodel.c 

signal_VS_realtime_signal:

signalset_with_signal_mask: tools.c menu.c 

signalset_with_binary_tree: tools.c menu.c

childwait:

sum_of_all_digits: sum_of_digits.c

sum_of_all_digits_realtime_signal: sum_of_digits.c

# my libs
menu:

tools:

clean:
	$(RM) *.o 
