CFLAGS += -W -Wall -pthread
all: what_is_with_mutex my_strtok sum_of_all_digits_threads


what_is_with_mutex:

my_strtok:

sum_of_digits:

sum_of_all_digits_threads: sum_of_digits.c

clean:
	$(RM) *.o what_is_with_mutex my_strtok sum_of_all_digits_threads
