Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.synced_folder ".", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
    echo "deb http://httpredir.debian.org/debian jessie main contrib" > /etc/apt/sources.list
    echo "deb-src http://httpredir.debian.org/debian jessie main contrib" >> /etc/apt/sources.list

    apt-get update
    apt-get -y upgrade
    apt-get install -y build-essential make cmake virtualbox-guest-dkms virtualbox-guest-x11 linux-headers-$(uname -r)
  SHELL
end
